### ISSUE TITLE
生成的短连接，直接打开为啥是空的

### ISSUE THREAD

**Issue by jetamie** [GallopYD/domain-tool#2]

**Comment by GallopYD** [comment]
短链接只是跳转到被检测的域名，内容是否为空取决于域名是否做了解析。
短链接访问的结果有3种：
1、微信拦截页面（域名被拦截）
2、被检测域名直接访问的页面（域名正常）
3、空白页（域名正常，未做解析）

**Comment by jetamie** [comment]
是这样的，我是找了一个已经被封了的域名，在微信打开是显示被拦截的，生成的短链接后打开空白
还有用百度的域名也是空白

**Comment by GallopYD** [comment]
用百度的域名生成短链接后，访问也是空白，只能说明你短链接生成错了，检查下参数是否正确。
这个是我用这个项目，生成的baidu.com的短链接：https://w.url.cn/s/AFwzyvX ，访问正常。

**Comment by jetamie** [comment]
我找到原因了，我把url参数urlencode了

**Comment by jetamie** [comment]
多谢

**Comment by GallopYD** [comment]
不客气
